"""
Purpose:
    Admin review model for moderated publishing and external report uploads.
Inputs:
    Review requests generated by publish workflows or external uploads.
Outputs:
    Review queue rows for platform admins and security reviewers.
Dependencies:
    SQLAlchemy Base and model column types.
TODO Checklist:
    - [ ] Add escalation reason codes if moderation policy gets more detailed.
    - [ ] Add attachment storage references for external uploads.
"""

from datetime import datetime, timezone
from uuid import uuid4

from sqlalchemy import DateTime, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


class AdminReview(Base):
    """Moderation/review queue entry for public sharing workflows."""

    __tablename__ = "admin_reviews"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid4()))
    review_type: Mapped[str] = mapped_column(String(32))
    submission_reference: Mapped[str] = mapped_column(String(64), index=True)
    status: Mapped[str] = mapped_column(String(32), default="pending")
    requested_action: Mapped[str] = mapped_column(String(32), default="publish")
    reviewer_notes: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
    )
    decided_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
